{% set data = load_setup_py_data() %}

package:
  name: "pymt_sedflux"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - sedflux 

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pymt
    - sedflux 

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt
    - pymt_sedflux
  commands:
    - config_file=$(mmd-stage Sedflux3D . > MANIFEST && mmd-query Sedflux3D --var=run.config_file.path)
    - bmi-test pymt_sedflux.bmi:Sedflux3D --infile=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage Avulsion . > MANIFEST && mmd-query Avulsion --var=run.config_file.path)
    - bmi-test pymt_sedflux.bmi:Avulsion --infile=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage Plume . > MANIFEST && mmd-query Plume --var=run.config_file.path)
    - bmi-test pymt_sedflux.bmi:Plume --infile=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage Subside . > MANIFEST && mmd-query Subside --var=run.config_file.path)
    - bmi-test pymt_sedflux.bmi:Subside --infile=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the sedflux BMI.
  home: https://github.com/mcflugen/pymt_sedflux
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_sedflux
