build:
  define_macros: []
  extra_compile_args: []
  include_dirs: []
  libraries:
  - bmi_sedflux3d
  - bmi_avulsion
  - bmi_plume
  - bmi_subside
  library_dirs: []
  undef_macros: []
info:
  github_username: mcflugen
  plugin_author: Eric Hutton
  plugin_license: MIT
  summary: PyMT plugin for sedflux
library:
  entry_point:
  - Sedflux3D=sedflux:register_bmi_sedflux3d
  - Avulsion=sedflux:register_bmi_avulsion
  - Plume=sedflux:register_bmi_plume
  - Subside=sedflux:register_bmi_subside
  language: c
  register: register_bmi_sedflux3d
plugin:
  name: sedflux
  requirements:
  - sedflux
