sediment_mass_concentration:
  description: Average mass-concentration of suspended sediment
  value:
    type: float
    default: 4.0
    units: kg/m^3
    range:
      min: 0.01
      max: 10.0

river_mouth_velocity:
  description: Flow velocity at river mouth
  value:
    type: float
    default: 1.0
    units: m/s
    range:
      min: 0.1
      max: 10.0

river_mouth_width:
  description: Width of river at river mouth
  value:
    type: float
    default: 100.0
    units: m
    range:
      min: 10.0
      max: 5000.0

river_mouth_depth:
  description: Depth of river at river mouth
  value:
    type: float
    default: 10.0
    units: m
    range:
      min: 1.0
      max: 100.0

river_mouth_angle:
  description: Angle of the river mouth measured with respect to the coast normal
  value:
    type: float
    default: 0.0
    units: degrees
    range:
      min: -180.0
      max: 180.0
  
river_mouth_latitude:
  description: Latitude of the river mouth
  value:
    type: float
    default: 45.0
    units: degrees
    range:
      min: -90.0
      max: 90.0
  
coast_normal:
  description: Angle of the coast normal as measured clockwise from north
  value:
    type: float
    default: 90.0
    units: degrees
    range:
      min: 0.0
      max: 360.0

basin_width:
  description: Width of the ocean/fjord
  value:
    type: float
    default: 2000.0
    units: m
    range:
      min: 100.0
      max: 200000.0
  
basin_length:
  description: Length of the ocean/fjord
  value:
    type: float
    default: 30000.0
    units: m
    range:
      min: 1000.0
      max: 200000.0
  
bulk_density:
  description: Saturated bulk density of bottom sediments
  value:
    type: float
    default: 1800.0
    units: kg/m^3
    range:
      min: 1000.0
      max: 2650.0

removal_rate:
  description: Removal rate of susmpended sediment
  value:
    type: float
    default: 16.8
    units: day^-1
    range:
      min: 1.0
      max: 100.0
  
background_ocean_concentration:
  description: Background sediment volume concentration of the ocean
  value:
    type: float
    default: 0.0
    units: "-"
    range:
      min: 0.0
      max: 1.0

normalized_current_width:
  description: Normalized width of the along-shore current
  value:
    type: float
    default: 1.0
    units: "-"
    range:
      min: 0.1
      max: 1.0

coastal_current_velocity:
  description: Along-shore velocity of the coastal current
  value:
    type: float
    default: 0.0
    units: m/s
    range:
      min: -5.0
      max: 5.0
  
grid_nodes_in_river_mouth:
  description: Number of computational grid nodes contained within the river mouth
  value:
    type: int
    default: 3
    units: "-"
    range:
      min: 3
      max: 21

ratio_of_cross_shore_to_along_shore_spacing:
  description: Ratio of spacing in the along-shore to cross-shore spacing
  value:
    type: int
    default: 2
    range:
      min: 1
      max: 20
    units: "-"

along_shore_resolution:
  description: Resolution of the deposit in the along-shore direction
  value:
    type: float
    default: 100.0
    units: m
    range:
      min: 100.0
      max: 1000.0

cross_shore_resolution:
  description: Resolution of the deposit in the cross-shore direction
  value:
    type: float
    default: 100.0
    units: m
    range:
      min: 100.0
      max: 1000.0
